In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('Average Income House Hold By Income.csv')

In [8]:
df.head()

,zipcodes,location,city,population,avg_Income,national Rank
0,15201,"40.474607, -79.952113",Pittsburgh,14326,27031,"#26,607"
1,15202,"40.506932, -80.069067",Pittsburgh,21022,34727,"#17,787"
2,15203,"40.425326, -79.976226",Pittsburgh,9613,27595,"#26,044"
3,15204,"40.456102, -80.063805",Pittsburgh,9502,32859,"#19,885"
4,15205,"40.437901, -80.097688",Pittsburgh,22586,38507,"#13,452"

In [9]:
import json, numpy, scipy.stats, string, sys

In [10]:
def biz_parse():
    ''' Parses yelp BUSINESS dataset - Extracting only restaurants. '''
    print "Parsing Business Data.  Getting business_id, review_count, name"
    jsonData = open("yelp_academic_dataset_business.json")
    bizData = {}
    categoryList = list()
    for line in jsonData:
    	data = json.loads(line)
    	business_id = data["business_id"]
    	review_count = data["review_count"]
    	name = data["name"]
    	categories = data["categories"]
        state = data["state"]
        opentime = data['hours']
        
        if len('hours')> 0:
    	    if "Tuesday" in opentime:
                try: opentime1 = opentime["Tuesday"]['open']
                except KeyError: opentime1 = "NA"
         
        closetime = data['hours']
        
        if len('hours')> 0:
    	    if "Tuesday" in closetime:
                try: closetime1 = opentime["Tuesday"]['close']
                except KeyError: opentime1 = "NA"
                
    	city = data["city"]
        
        zipcodes = data['full_address'][-6:]
    	latitude = data["latitude"]
    	longitude = data["longitude"]
        stars = data["stars"]
        attributes =  data["attributes"]
    	
    	if len(categories)> 0:
    	    if "Restaurants" in categories:
		try: priceRange = attributes["Price Range"]
                except KeyError: priceRange = "NA"
                try: NoiseLevel = attributes["Noise Level"]
                except KeyError: NoiseLevel = "NA"
                try: Delivery = attributes["Delivery"]
                except KeyError: Delivery = "NA"
		bizData[business_id] = [review_count, name, categories, opentime1, closetime1, state, city, zipcodes, latitude, longitude, stars, priceRange, NoiseLevel, Delivery]
    	        categoryList += categories
    print len(bizData), "businesses added"
    return bizData

In [11]:
data=pd.DataFrame(biz_parse())

Parsing Business Data.  Getting business_id, review_count, name
21892 businesses added

In [12]:
data1 = data.transpose()

In [13]:
#data1

In [14]:
data1.columns = ['review_count', 'name', 'categories', 'opentime','closetime', 'state', 'city', 'zipcodes','latitude', 'longitude', 'stars','priceRange', 'noiselevel', 'delivery']
#data1

In [15]:
datapit = data1[data1['city'] == 'Pittsburgh']

In [16]:
datacom = pd.read_csv('combined.csv')

In [17]:
datacom

,review_count,categories,opentime,closetime,stars,priceRange,noiselevel,delivery,zipcodes,avg_Income,population
0,103,"[Diners, Restaurants]",0:00,0:00,3.5,1,average,False,15224,22880,12095
1,26,"[Chinese, Restaurants]",11:00,21:00,3.0,2,average,False,15222,18598,1999
2,41,"[Bars, American (Traditional), Pubs, Nightlife...",11:00,2:00,3.0,2,average,False,15222,18598,1999
3,3,"[Delis, Comfort Food, Restaurants]",11:00,18:00,3.5,0,NaN,NaN,15222,18598,1999
4,14,"[Chinese, Restaurants]",11:00,22:00,4.0,1,quiet,True,15227,38439,29621
5,3,"[Restaurants, Mediterranean, Turkish]",8:00,21:00,4.0,2,quiet,True,15213,18473,28320
6,67,"[Seafood, Restaurants]",10:00,22:00,3.0,1,average,False,15222,18598,1999
7,179,"[American (New), Restaurants]",17:00,22:00,4.0,3,average,False,15206,28517,32482
8,40,"[Bars, Restaurants, Nightlife, Italian]",11:00,2:00,3.0,2,average,False,15224,22880,12095
9,7,"[Steakhouses, Restaurants]",10:00,17:00,2.5,1,loud,False,15222,18598,1999
10,5,"[Caribbean, Restaurants]",11:00,22:00,4.0,1,quiet,False,15221,30668,36387
11,65,"[Chinese, Restaurants]",11:00,21:30,3.5,2,quiet,True,15219,14399,19204
12,61,"[Moroccan, Restaurants]",17:00,22:00,4.5,2,average,False,15228,58440,17723
13,70,"[Indian, Restaurants]",11:30,22:00,3.0,2,average,True,15217,45173,26425
14,126,"[Korean, Sushi Bars, Japanese, Restaurants]",10:30,21:00,4.0,1,average,False,15213,18473,28320
15,227,"[Vegetarian, American (Traditional), Barbeque,...",11:00,2:00,3.5,2,average,False,15203,27595,9613
16,60,"[Health Markets, Food, Vegetarian, Restaurants...",8:00,21:00,4.5,2,average,False,15208,24178,13352
17,9,"[Food, Sandwiches, Bagels, Breakfast & Brunch,...",5:30,17:00,3.0,1,quiet,False,15219,14399,19204
18,3,"[Pizza, Restaurants]",11:00,21:00,3.5,0,quiet,NaN,15212,26712,31850
19,12,"[Sandwiches, Restaurants]",7:00,17:00,4.0,2,quiet,False,15238,67370,13571
20,15,"[American (New), Restaurants]",17:00,21:00,4.0,2,average,False,15202,34727,21022
21,399,"[American (Traditional), Restaurants]",11:00,0:00,4.0,2,loud,False,15203,27595,9613
22,32,"[Italian, Pizza, Restaurants]",9:00,21:00,4.0,1,average,True,15222,18598,1999
23,11,"[Restaurants, Italian]",8:00,21:00,3.5,2,average,True,15236,46913,30630
24,3,"[Diners, Restaurants]",8:30,17:00,4.0,0,NaN,NaN,15220,44018,19693
25,32,"[Caterers, Event Planning & Services, Barbeque...",11:00,20:00,4.0,2,quiet,False,15216,39526,24691
26,56,"[American (Traditional), Restaurants]",17:00,23:00,3.5,2,quiet,False,15232,32552,11792
27,49,"[Steakhouses, Restaurants]",11:30,22:00,4.0,4,average,False,15222,18598,1999
28,96,"[Breakfast & Brunch, American (New), Restaurants]",7:00,15:00,4.0,2,average,True,15222,18598,1999
29,33,"[Restaurants, Italian]",17:00,23:00,4.0,3,quiet,True,15213,18473,28320
...,...,...,...,...,...,...,...,...,...,...,...
1167,5,"[Food, Juice Bars & Smoothies, Restaurants]",17:00,22:00,4.5,0,NaN,NaN,15219,14399,19204
1168,20,"[Delis, Restaurants]",9:00,17:00,4.0,1,average,False,15222,18598,1999
1169,93,"[Vegetarian, Vietnamese, Restaurants]",11:30,22:00,4.0,2,average,False,15217,45173,26425
1170,135,"[Bars, Food, Beer, Wine & Spirits, Tapas/Small...",17:00,0:00,4.0,2,average,False,15222,18598,1999
1171,6,"[Bakeries, Food, Cafes, Restaurants]",6:00,22:00,4.5,2,NaN,False,15222,18598,1999
1172,64,"[Bars, American (Traditional), Delis, Nightlif...",10:00,23:00,4.0,1,average,True,15203,27595,9613
1173,10,"[Pizza, Mediterranean, Restaurants]",10:00,22:00,4.5,2,average,True,15215,43750,13212
1174,3,"[American (Traditional), Fast Food, Restaurants]",17:00,23:00,2.5,1,NaN,NaN,15213,18473,28320
1175,26,"[Fast Food, Mexican, Restaurants]",17:00,22:00,4.0,1,average,False,15222,18598,1999
1176,8,"[Bars, American (Traditional), Nightlife, Rest...",16:00,2:00,4.0,1,quiet,False,15217,45173,26425
1177,10,"[Food, Burgers, Hot Dogs, Desserts, Restaurants]",11:00,21:00,4.0,2,average,False,15228,58440,17723
1178,5,"[Food, Soup, Juice Bars & Smoothies, Salad, Re...",11:00,18:00,4.5,1,quiet,False,15222,18598,1999
1179,20,"[Szechuan, Chinese, Restaurants]",11:00,22:00,4.0,2,quiet,True,15213,18473,28320
1180,4,"[Cafes, Restaurants]",8:00,16:00,4.0,0,NaN,NaN,15219,14399,19204
1181,47,"[Bars, American (Traditional), Nightlife, Rest...",11:00,2:00,4.0,1,average,False,15203,27595,9613
1182,22,"[Pizza, Restaurants]",10:00,1:00,4.0,1,average,True,15232,32552,11792
1183,6,"[Pizza, Restaurants]",12:00,20:00,3.0,2,quiet,True,15212,26712,31850
1184,8,"[Thai, Filipino, Restaurants]",11:00,15:00,3.5,2,NaN,True,15217,45173,26425
1185,15,"[Middle Eastern, Halal, Restaurants]",11:00,22:00,4.5,2,quiet,False,15201,27031,14326
1186,5,"[Bars, American (Traditional), Nightlife, Loun...",12:00,2:00,2.5,1,average,NaN,15222,18598,1999
1187,74,"[Seafood, Restaurants]",11:00,23:00,2.5,3,quiet,False,15222,18598,1999
1188,75,"[Burgers, Gastropubs, Restaurants]",11:30,22:00,3.5,2,average,False,15233,23841,4876
1189,24,"[Delis, American (Traditional), Sandwiches, Re...",11:00,2:00,3.5,2,average,False,15232,32552,11792
1190,9,"[Chinese, Restaurants]",11:00,21:00,3.5,2,quiet,False,15222,18598,1999
1191,26,"[Pizza, Restaurants]",11:00,22:00,3.0,2,average,True,15217,45173,26425
1192,21,"[Bars, American (Traditional), Nightlife, Rest...",16:00,22:30,4.0,2,average,False,15234,40756,14911
1193,200,"[Bars, Mexican, Nightlife, Restaurants]",11:30,0:00,3.5,2,loud,False,15201,27031,14326
1194,13,"[Breakfast & Brunch, Restaurants]",10:00,21:00,3.5,1,NaN,False,15206,28517,32482
1195,6,"[American (New), Restaurants]",11:00,22:00,3.0,2,quiet,False,15213,18473,28320
1196,19,"[Restaurants, Italian]",11:00,22:00,3.5,2,average,False,15220,44018,19693

a=0
for i in datacom['categories']:
    a = a+1
    if 'Delis' in i:
        datacom['categories'][a-1] = 'Deli'
    elif 'Sandwiches' in i:
        datacom['categories'][a-1] = 'Sandwiches'
    elif 'Burgers' in i:
        datacom['categories'][a-1] = 'Burgers'
    elif 'Chinese' in i:
        datacom['categories'][a-1] = 'Chinese'
    elif 'Seafood' in i:
        datacom['categories'][a-1] = 'Seafood'
    elif 'American'in i:
        datacom['categories'][a-1] = 'American'
    elif 'Pizza'in i:
        datacom['categories'][a-1] = 'Pizza'
    elif 'Steakhouses'in i:
        datacom['categories'][a-1] = 'Steakhouses'
    elif 'Korean' in i:
        datacom['categories'][a-1] = 'Japanese'
    elif 'Japanese' in i:
        datacom['categories'][a-1] = 'Japanese'
    elif 'Italian' in i:
        datacom['categories'][a-1] = 'Italian'
    elif 'Mexican' in i:
        datacom['categories'][a-1] = 'Mexican'
    elif 'Thai' in i:
        datacom['categories'][a-1] = 'Thai'
    elif 'Middle Eastern' in i:
        datacom['categories'][a-1] = 'Middle Eastern'
    else:
        datacom['categories'][a-1] = 'Others'

In [18]:
datacom

,review_count,categories,opentime,closetime,stars,priceRange,noiselevel,delivery,zipcodes,avg_Income,population
0,103,"[Diners, Restaurants]",0:00,0:00,3.5,1,average,False,15224,22880,12095
1,26,"[Chinese, Restaurants]",11:00,21:00,3.0,2,average,False,15222,18598,1999
2,41,"[Bars, American (Traditional), Pubs, Nightlife...",11:00,2:00,3.0,2,average,False,15222,18598,1999
3,3,"[Delis, Comfort Food, Restaurants]",11:00,18:00,3.5,0,NaN,NaN,15222,18598,1999
4,14,"[Chinese, Restaurants]",11:00,22:00,4.0,1,quiet,True,15227,38439,29621
5,3,"[Restaurants, Mediterranean, Turkish]",8:00,21:00,4.0,2,quiet,True,15213,18473,28320
6,67,"[Seafood, Restaurants]",10:00,22:00,3.0,1,average,False,15222,18598,1999
7,179,"[American (New), Restaurants]",17:00,22:00,4.0,3,average,False,15206,28517,32482
8,40,"[Bars, Restaurants, Nightlife, Italian]",11:00,2:00,3.0,2,average,False,15224,22880,12095
9,7,"[Steakhouses, Restaurants]",10:00,17:00,2.5,1,loud,False,15222,18598,1999
10,5,"[Caribbean, Restaurants]",11:00,22:00,4.0,1,quiet,False,15221,30668,36387
11,65,"[Chinese, Restaurants]",11:00,21:30,3.5,2,quiet,True,15219,14399,19204
12,61,"[Moroccan, Restaurants]",17:00,22:00,4.5,2,average,False,15228,58440,17723
13,70,"[Indian, Restaurants]",11:30,22:00,3.0,2,average,True,15217,45173,26425
14,126,"[Korean, Sushi Bars, Japanese, Restaurants]",10:30,21:00,4.0,1,average,False,15213,18473,28320
15,227,"[Vegetarian, American (Traditional), Barbeque,...",11:00,2:00,3.5,2,average,False,15203,27595,9613
16,60,"[Health Markets, Food, Vegetarian, Restaurants...",8:00,21:00,4.5,2,average,False,15208,24178,13352
17,9,"[Food, Sandwiches, Bagels, Breakfast & Brunch,...",5:30,17:00,3.0,1,quiet,False,15219,14399,19204
18,3,"[Pizza, Restaurants]",11:00,21:00,3.5,0,quiet,NaN,15212,26712,31850
19,12,"[Sandwiches, Restaurants]",7:00,17:00,4.0,2,quiet,False,15238,67370,13571
20,15,"[American (New), Restaurants]",17:00,21:00,4.0,2,average,False,15202,34727,21022
21,399,"[American (Traditional), Restaurants]",11:00,0:00,4.0,2,loud,False,15203,27595,9613
22,32,"[Italian, Pizza, Restaurants]",9:00,21:00,4.0,1,average,True,15222,18598,1999
23,11,"[Restaurants, Italian]",8:00,21:00,3.5,2,average,True,15236,46913,30630
24,3,"[Diners, Restaurants]",8:30,17:00,4.0,0,NaN,NaN,15220,44018,19693
25,32,"[Caterers, Event Planning & Services, Barbeque...",11:00,20:00,4.0,2,quiet,False,15216,39526,24691
26,56,"[American (Traditional), Restaurants]",17:00,23:00,3.5,2,quiet,False,15232,32552,11792
27,49,"[Steakhouses, Restaurants]",11:30,22:00,4.0,4,average,False,15222,18598,1999
28,96,"[Breakfast & Brunch, American (New), Restaurants]",7:00,15:00,4.0,2,average,True,15222,18598,1999
29,33,"[Restaurants, Italian]",17:00,23:00,4.0,3,quiet,True,15213,18473,28320
...,...,...,...,...,...,...,...,...,...,...,...
1167,5,"[Food, Juice Bars & Smoothies, Restaurants]",17:00,22:00,4.5,0,NaN,NaN,15219,14399,19204
1168,20,"[Delis, Restaurants]",9:00,17:00,4.0,1,average,False,15222,18598,1999
1169,93,"[Vegetarian, Vietnamese, Restaurants]",11:30,22:00,4.0,2,average,False,15217,45173,26425
1170,135,"[Bars, Food, Beer, Wine & Spirits, Tapas/Small...",17:00,0:00,4.0,2,average,False,15222,18598,1999
1171,6,"[Bakeries, Food, Cafes, Restaurants]",6:00,22:00,4.5,2,NaN,False,15222,18598,1999
1172,64,"[Bars, American (Traditional), Delis, Nightlif...",10:00,23:00,4.0,1,average,True,15203,27595,9613
1173,10,"[Pizza, Mediterranean, Restaurants]",10:00,22:00,4.5,2,average,True,15215,43750,13212
1174,3,"[American (Traditional), Fast Food, Restaurants]",17:00,23:00,2.5,1,NaN,NaN,15213,18473,28320
1175,26,"[Fast Food, Mexican, Restaurants]",17:00,22:00,4.0,1,average,False,15222,18598,1999
1176,8,"[Bars, American (Traditional), Nightlife, Rest...",16:00,2:00,4.0,1,quiet,False,15217,45173,26425
1177,10,"[Food, Burgers, Hot Dogs, Desserts, Restaurants]",11:00,21:00,4.0,2,average,False,15228,58440,17723
1178,5,"[Food, Soup, Juice Bars & Smoothies, Salad, Re...",11:00,18:00,4.5,1,quiet,False,15222,18598,1999
1179,20,"[Szechuan, Chinese, Restaurants]",11:00,22:00,4.0,2,quiet,True,15213,18473,28320
1180,4,"[Cafes, Restaurants]",8:00,16:00,4.0,0,NaN,NaN,15219,14399,19204
1181,47,"[Bars, American (Traditional), Nightlife, Rest...",11:00,2:00,4.0,1,average,False,15203,27595,9613
1182,22,"[Pizza, Restaurants]",10:00,1:00,4.0,1,average,True,15232,32552,11792
1183,6,"[Pizza, Restaurants]",12:00,20:00,3.0,2,quiet,True,15212,26712,31850
1184,8,"[Thai, Filipino, Restaurants]",11:00,15:00,3.5,2,NaN,True,15217,45173,26425
1185,15,"[Middle Eastern, Halal, Restaurants]",11:00,22:00,4.5,2,quiet,False,15201,27031,14326
1186,5,"[Bars, American (Traditional), Nightlife, Loun...",12:00,2:00,2.5,1,average,NaN,15222,18598,1999
1187,74,"[Seafood, Restaurants]",11:00,23:00,2.5,3,quiet,False,15222,18598,1999
1188,75,"[Burgers, Gastropubs, Restaurants]",11:30,22:00,3.5,2,average,False,15233,23841,4876
1189,24,"[Delis, American (Traditional), Sandwiches, Re...",11:00,2:00,3.5,2,average,False,15232,32552,11792
1190,9,"[Chinese, Restaurants]",11:00,21:00,3.5,2,quiet,False,15222,18598,1999
1191,26,"[Pizza, Restaurants]",11:00,22:00,3.0,2,average,True,15217,45173,26425
1192,21,"[Bars, American (Traditional), Nightlife, Rest...",16:00,22:30,4.0,2,average,False,15234,40756,14911
1193,200,"[Bars, Mexican, Nightlife, Restaurants]",11:30,0:00,3.5,2,loud,False,15201,27031,14326
1194,13,"[Breakfast & Brunch, Restaurants]",10:00,21:00,3.5,1,NaN,False,15206,28517,32482
1195,6,"[American (New), Restaurants]",11:00,22:00,3.0,2,quiet,False,15213,18473,28320
1196,19,"[Restaurants, Italian]",11:00,22:00,3.5,2,average,False,15220,44018,19693

In [19]:
data1 =  datacom['categories'].groupby(datacom['categories']).count()
data1

categories
[Active Life, Restaurants]                                                                     1
[American (New), Buffets, Barbeque, Restaurants]                                               1
[American (New), Cafes, Restaurants]                                                           1
[American (New), Diners, Restaurants]                                                          1
[American (New), Event Planning & Services, Venues & Event Spaces, Restaurants]                1
[American (New), Mediterranean, Restaurants]                                                   3
[American (New), Mexican, Restaurants]                                                         2
[American (New), Restaurants]                                                                 57
[American (New), Sandwiches, Restaurants]                                                      1
[American (New), Sandwiches, Salad, Restaurants]                                               1
[American (Traditional), American (New), Restaurants]                                          3
[American (Traditional), Barbeque, Restaurants]                                                1
[American (Traditional), Buffets, Chicken Wings, Restaurants]                                  1
[American (Traditional), Diners, Restaurants]                                                  2
[American (Traditional), Fast Food, Restaurants]                                               1
[American (Traditional), Hot Dogs, Restaurants]                                                1
[American (Traditional), Pizza, Restaurants]                                                   1
[American (Traditional), Restaurants]                                                         41
[American (Traditional), Sandwiches, Restaurants]                                              2
[American (Traditional), Steakhouses, Diners, Restaurants]                                     1
[American (Traditional), Steakhouses, Seafood, Restaurants]                                    1
[American (Traditional), Tex-Mex, Restaurants]                                                 1
[Arts & Entertainment, American (Traditional), Music Venues, Bars, Nightlife, Restaurants]     2
[Arts & Entertainment, Bars, Casinos, Nightlife, Steakhouses, Sports Bars, Restaurants]        1
[Arts & Entertainment, Cafes, Arcades, Restaurants]                                            1
[Arts & Entertainment, Music Venues, Burgers, Nightlife, American (New), Restaurants]          1
[Arts & Entertainment, Music Venues, Cafes, Bars, Nightlife, Lounges, Restaurants]             1
[Arts & Entertainment, Nightlife, Jazz & Blues, Gastropubs, American (New), Restaurants]       1
[Asian Fusion, American (New), Restaurants]                                                    1
[Asian Fusion, Buffets, Chinese, Restaurants]                                                  1
                                                                                              ..
[Tapas/Small Plates, Restaurants, Italian]                                                     1
[Tapas/Small Plates, Restaurants]                                                              1
[Tapas/Small Plates, Vegetarian, Latin American, Restaurants]                                  1
[Thai, Asian Fusion, Filipino, Restaurants]                                                    1
[Thai, Cafes, Restaurants]                                                                     1
[Thai, Cambodian, Restaurants]                                                                 1
[Thai, Chinese, Restaurants]                                                                   1
[Thai, Filipino, Restaurants]                                                                  1
[Thai, Restaurants]                                                                           28
[Thai, Sushi Bars, Japanese, Restaurants]                                                      1
[Thai, Tapas Bars, Restaurants]                                                                1
[Turkish, Mediterranean, Restaurants]                                                          2
[Turkish, Middle Eastern, Pizza, Restaurants]                                                  1
[Turkish, Middle Eastern, Restaurants]                                                         1
[Turkish, Pizza, Restaurants]                                                                  1
[Uzbek, Restaurants]                                                                           1
[Uzbek, Russian, Halal, Restaurants]                                                           1
[Vegetarian, American (Traditional), Barbeque, Restaurants]                                    1
[Vegetarian, Ethiopian, Vegan, Restaurants]                                                    1
[Vegetarian, Hot Dogs, Restaurants]                                                            1
[Vegetarian, Korean, Japanese, Chinese, Restaurants]                                           1
[Vegetarian, Mediterranean, Vegan, Restaurants]                                                1
[Vegetarian, Middle Eastern, Vegan, Restaurants]                                               1
[Vegetarian, Vegan, Salad, Restaurants]                                                        1
[Vegetarian, Vietnamese, Restaurants]                                                          1
[Vietnamese, Japanese, Chinese, Restaurants]                                                   1
[Vietnamese, Restaurants]                                                                      6
[Wine Bars, Bars, American (New), Nightlife, Restaurants]                                      2
[Wine Bars, Bars, Mediterranean, Nightlife, Restaurants]                                       1
[Wine Bars, Bars, Restaurants, Nightlife, Italian]                                             1
dtype: int64

In [3]:
import numpy as np
import pandas as pd

In [4]:
datacom = pd.read_csv('out.csv')
datacom

,Unnamed: 0,review_count,categories,opentime,closetime,stars,priceRange,noiselevel,delivery,zipcodes,avg_Income,population
0,0,103,Others,0:00,0:00,3.5,1,average,False,15224,22880,12095
1,1,26,Chinese,11:00,21:00,3.0,2,average,False,15222,18598,1999
2,2,41,American,11:00,2:00,3.0,2,average,False,15222,18598,1999
3,3,3,Deli,11:00,18:00,3.5,0,NaN,NaN,15222,18598,1999
4,4,14,Chinese,11:00,22:00,4.0,1,quiet,True,15227,38439,29621
5,5,3,Others,8:00,21:00,4.0,2,quiet,True,15213,18473,28320
6,6,67,Seafood,10:00,22:00,3.0,1,average,False,15222,18598,1999
7,7,179,American,17:00,22:00,4.0,3,average,False,15206,28517,32482
8,8,40,Italian,11:00,2:00,3.0,2,average,False,15224,22880,12095
9,9,7,Steakhouses,10:00,17:00,2.5,1,loud,False,15222,18598,1999
10,10,5,Others,11:00,22:00,4.0,1,quiet,False,15221,30668,36387
11,11,65,Chinese,11:00,21:30,3.5,2,quiet,True,15219,14399,19204
12,12,61,Others,17:00,22:00,4.5,2,average,False,15228,58440,17723
13,13,70,Others,11:30,22:00,3.0,2,average,True,15217,45173,26425
14,14,126,Japanese,10:30,21:00,4.0,1,average,False,15213,18473,28320
15,15,227,American,11:00,2:00,3.5,2,average,False,15203,27595,9613
16,16,60,Others,8:00,21:00,4.5,2,average,False,15208,24178,13352
17,17,9,Sandwiches,5:30,17:00,3.0,1,quiet,False,15219,14399,19204
18,18,3,Pizza,11:00,21:00,3.5,0,quiet,NaN,15212,26712,31850
19,19,12,Sandwiches,7:00,17:00,4.0,2,quiet,False,15238,67370,13571
20,20,15,American,17:00,21:00,4.0,2,average,False,15202,34727,21022
21,21,399,American,11:00,0:00,4.0,2,loud,False,15203,27595,9613
22,22,32,Pizza,9:00,21:00,4.0,1,average,True,15222,18598,1999
23,23,11,Italian,8:00,21:00,3.5,2,average,True,15236,46913,30630
24,24,3,Others,8:30,17:00,4.0,0,NaN,NaN,15220,44018,19693
25,25,32,Others,11:00,20:00,4.0,2,quiet,False,15216,39526,24691
26,26,56,American,17:00,23:00,3.5,2,quiet,False,15232,32552,11792
27,27,49,Steakhouses,11:30,22:00,4.0,4,average,False,15222,18598,1999
28,28,96,American,7:00,15:00,4.0,2,average,True,15222,18598,1999
29,29,33,Italian,17:00,23:00,4.0,3,quiet,True,15213,18473,28320
...,...,...,...,...,...,...,...,...,...,...,...,...
1167,1167,5,Others,17:00,22:00,4.5,0,NaN,NaN,15219,14399,19204
1168,1168,20,Deli,9:00,17:00,4.0,1,average,False,15222,18598,1999
1169,1169,93,Others,11:30,22:00,4.0,2,average,False,15217,45173,26425
1170,1170,135,Others,17:00,0:00,4.0,2,average,False,15222,18598,1999
1171,1171,6,Others,6:00,22:00,4.5,2,NaN,False,15222,18598,1999
1172,1172,64,Deli,10:00,23:00,4.0,1,average,True,15203,27595,9613
1173,1173,10,Pizza,10:00,22:00,4.5,2,average,True,15215,43750,13212
1174,1174,3,American,17:00,23:00,2.5,1,NaN,NaN,15213,18473,28320
1175,1175,26,Mexican,17:00,22:00,4.0,1,average,False,15222,18598,1999
1176,1176,8,American,16:00,2:00,4.0,1,quiet,False,15217,45173,26425
1177,1177,10,Burgers,11:00,21:00,4.0,2,average,False,15228,58440,17723
1178,1178,5,Others,11:00,18:00,4.5,1,quiet,False,15222,18598,1999
1179,1179,20,Chinese,11:00,22:00,4.0,2,quiet,True,15213,18473,28320
1180,1180,4,Others,8:00,16:00,4.0,0,NaN,NaN,15219,14399,19204
1181,1181,47,American,11:00,2:00,4.0,1,average,False,15203,27595,9613
1182,1182,22,Pizza,10:00,1:00,4.0,1,average,True,15232,32552,11792
1183,1183,6,Pizza,12:00,20:00,3.0,2,quiet,True,15212,26712,31850
1184,1184,8,Thai,11:00,15:00,3.5,2,NaN,True,15217,45173,26425
1185,1185,15,Middle Eastern,11:00,22:00,4.5,2,quiet,False,15201,27031,14326
1186,1186,5,American,12:00,2:00,2.5,1,average,NaN,15222,18598,1999
1187,1187,74,Seafood,11:00,23:00,2.5,3,quiet,False,15222,18598,1999
1188,1188,75,Burgers,11:30,22:00,3.5,2,average,False,15233,23841,4876
1189,1189,24,Deli,11:00,2:00,3.5,2,average,False,15232,32552,11792
1190,1190,9,Chinese,11:00,21:00,3.5,2,quiet,False,15222,18598,1999
1191,1191,26,Pizza,11:00,22:00,3.0,2,average,True,15217,45173,26425
1192,1192,21,American,16:00,22:30,4.0,2,average,False,15234,40756,14911
1193,1193,200,Mexican,11:30,0:00,3.5,2,loud,False,15201,27031,14326
1194,1194,13,Others,10:00,21:00,3.5,1,NaN,False,15206,28517,32482
1195,1195,6,American,11:00,22:00,3.0,2,quiet,False,15213,18473,28320
1196,1196,19,Italian,11:00,22:00,3.5,2,average,False,15220,44018,19693

categorieslist=['American','Burgers','Chinese','Deli','Italian','Japanese','Mexican','Middle Eastern','Others','Pizza','Sandwiches','Seafood','Steakhouses','Thai']
for i in datacom['competition']:
    for category in categorieslist:
        datacom['competition']=  datacom[category].groupby(datacom['zipcodes']).count()

In [5]:
datacom.noiselevel

0       average
1       average
2       average
3           NaN
4         quiet
5         quiet
6       average
7       average
8       average
9          loud
10        quiet
11        quiet
12      average
13      average
14      average
15      average
16      average
17        quiet
18        quiet
19        quiet
20      average
21         loud
22      average
23      average
24          NaN
25        quiet
26        quiet
27      average
28      average
29        quiet
         ...
1167        NaN
1168    average
1169    average
1170    average
1171        NaN
1172    average
1173    average
1174        NaN
1175    average
1176      quiet
1177    average
1178      quiet
1179      quiet
1180        NaN
1181    average
1182    average
1183      quiet
1184        NaN
1185      quiet
1186    average
1187      quiet
1188    average
1189    average
1190      quiet
1191    average
1192    average
1193       loud
1194        NaN
1195      quiet
1196    average
Name: noiselevel, dtype: object

In [ ]:
#datacom.to_csv('out.csv',encoding = 'utf-8')

In [110]:
data1 = datacom.groupby(['categories', 'zipcodes']).count()

In [131]:
1 = data1.index[1]

('American', 15202)

In [132]:
type(1)

int

In [117]:
data1['categories']

KeyError: 'categories'

In [75]:
print datacom['competition']

0       1197
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
20         0
21         0
22         0
23         0
24         0
25         0
26         0
27         0
28         0
29         0
        ...
1168       0
1169       0
1170       0
1171       0
1172       0
1173       0
1174       0
1175       0
1176       0
1177       0
1178       0
1179       0
1180       0
1181       0
1182       0
1183       0
1184       0
1185       0
1186       0
1187       0
1188       0
1189       0
1190       0
1191       0
1192       0
1193       0
1194       0
1195       0
1196       0
1197    1197
Name: competition, dtype: float64